name: civic_lens
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  geocoding: ^3.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  # UI & Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  animate_do: ^3.3.4

  # Maps
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0

  # AI & Camera
  image_picker: ^1.0.4
  google_generative_ai: ^0.4.0

  # Backend
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: "launcher_icon" # The name of the icon file on Android
  ios: true # Generate for iOS
  image_path: "assets/icon/icon.png" # ðŸ‘ˆ PATH TO MASTER IMAGE
  min_sdk_android: 21 # Helps with newer Android icon styles
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hex_code"
    theme_color: "#hex_code" 